#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  generate_dockerfile.sh BASE_YAML OVERLAY_YAML DOCKERFILE_HEADER OUT_DOCKERFILE [TOOLS_YAML]

Example:
  ./generate_dockerfile.sh \
    base.yaml \
    install-linux.yaml \
    Dockerfile.header \
    Dockerfile.generated \
    /tmp/tools.yaml
EOF
  exit 1
}

die() {
  echo "Error: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

json_quote() {
  jq -Rn --arg s "$1" '$s'
}

if [ "$#" -lt 4 ] || [ "$#" -gt 5 ]; then
  usage
fi

BASE_YAML=$1
OVERLAY_YAML=$2
DOCKERFILE_HEADER=$3
OUT_DOCKERFILE=$4
TOOLS_YAML=${5:-/tmp/tools.yaml}

need_cmd yq
need_cmd jq
need_cmd base64
need_cmd sed
need_cmd dirname
need_cmd mktemp

[ -f "$BASE_YAML" ] || die "base yaml not found: $BASE_YAML"
[ -f "$OVERLAY_YAML" ] || die "overlay yaml not found: $OVERLAY_YAML"
[ -f "$DOCKERFILE_HEADER" ] || die "Dockerfile header not found: $DOCKERFILE_HEADER"

mkdir -p "$(dirname "$OUT_DOCKERFILE")"
mkdir -p "$(dirname "$TOOLS_YAML")"

tmp_out="$(mktemp)"
trap 'rm -f "$tmp_out"' EXIT

echo "Merging YAML into $TOOLS_YAML" >&2
yq -s '.[0] * .[1]' "$BASE_YAML" "$OVERLAY_YAML" > "$TOOLS_YAML"

# Validate structure early.
yq -e '.tools | type == "object"' "$TOOLS_YAML" >/dev/null 2>&1 \
  || die "merged YAML must contain a top-level .tools mapping"

cat "$DOCKERFILE_HEADER" > "$tmp_out"

cat >> "$tmp_out" <<EOF

# ------------------------------------------------------------------
# Generated by generate_dockerfile.sh
# Base YAML:    $BASE_YAML
# Overlay YAML: $OVERLAY_YAML
# Merged YAML:  $TOOLS_YAML
# ------------------------------------------------------------------

EOF

tool_count=0

# Deterministic order by tool name.
while IFS= read -r tool_b64; do
  tool_json="$(printf '%s' "$tool_b64" | base64 -d)"

  name="$(printf '%s\n' "$tool_json" | jq -r '.key')"
  test_cmd="$(printf '%s\n' "$tool_json" | jq -r '.value.test // empty')"

  [ -n "$test_cmd" ] || die "tool '$name' is missing .test"

  # Normalize install to an array of commands:
  # null    -> []
  # string  -> [string]
  # array   -> array
  install_lines="$(
    printf '%s\n' "$tool_json" \
      | jq -r '
          .value.install
          | if . == null then []
            elif type == "string" then [.]
            elif type == "array" then .
            else error("install must be null, string, or array")
            end
          | .[]
        '
  )" || die "tool '$name' has invalid .install"

  name_q="$(json_quote "$name")"
  test_q="$(json_quote "$test_cmd")"

  {
    echo "RUN set -eu; \\"
    echo "    NAME=$name_q; \\"

    if [ -n "$install_lines" ]; then
      i=0
      while IFS= read -r install_cmd; do
        [ -n "$install_cmd" ] || continue
        install_q="$(json_quote "$install_cmd")"
        if [ "$i" -eq 0 ]; then
          echo "    echo \"=== \$NAME: install ===\"; \\"
        fi
        echo "    sh -c $install_q; \\"
        i=$((i + 1))
      done <<< "$install_lines"
    else
      echo "    echo \"=== \$NAME: no install step ===\"; \\"
    fi

    echo "    echo \"=== \$NAME: test ===\"; \\"
    echo "    sh -c $test_q"
    echo
  } >> "$tmp_out"

  tool_count=$((tool_count + 1))
  echo "Added tool step: $name" >&2
done < <(
  yq -r '.tools | to_entries | sort_by(.key)[] | @base64' "$TOOLS_YAML"
)

[ "$tool_count" -gt 0 ] || die "no tools found in merged YAML"

mv "$tmp_out" "$OUT_DOCKERFILE"

echo "Done." >&2
echo "Merged tools file: $TOOLS_YAML" >&2
echo "Generated Dockerfile: $OUT_DOCKERFILE" >&2
echo "Tool steps: $tool_count" >&2
